# ==========================================
# Test github workflow
#
#  v1.0
# ==========================================
name: Test_workflow
env:
  APP_NAME  : "Super Applikation"
  APP_VER   : "${{ github.sha }}"

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print APP
        run: |
          echo "Application - ${{ env.APP_NAME }}"
          echo "Version - ${{ env.APP_VER }}"
          
      - name: Clone my repo
        uses: actions/checkout@v2
      
      - name: List dir
        run: ls -al

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
      - name: Print APP
        run: |
          echo "Application - ${{ env.APP_NAME }}"
          echo "Version - ${{ env.APP_VER }}"
                
      - name: List dir
        run: ls -al

      - name: AWS
        run: aws --version
    
